#ANALSYS.

SELECT * FROM us_household_income;

#CANTIDAD DE CIUDADES POR ESTADO
SELECT STATE_NAME, COUNT(CITY) TOTAL_CITIES
FROM us_household_income
GROUP BY STATE_NAME
ORDER BY TOTAL_CITIES DESC
;
#CANTIDAD DE COUNTIES POR ESTADO 
SELECT STATE_NAME, COUNT(COUNTY) TOTAL_COUNTIES
FROM us_household_income
GROUP BY STATE_NAME
ORDER BY TOTAL_COUNTIES DESC;

#CANTIDAD DE ZIP CODES POR ESTADOS
SELECT STATE_NAME, COUNT(ZIP_CODE) TOTAL_ZIP_CODES
FROM us_household_income
GROUP BY STATE_NAME
ORDER BY TOTAL_ZIP_CODES DESC;

#TOP 5 ESTADOS CON MAS LAND
SELECT STATE_NAME, SUM(ALAND) TOTAL_LAND
FROM us_household_income
GROUP BY STATE_NAME
ORDER BY TOTAL_LAND DESC;

#TOP 5 ESTADOS CON MAS AGUA
SELECT STATE_NAME, SUM(AWATER) TOTAL_WATER
FROM us_household_income
GROUP BY STATE_NAME
ORDER BY TOTAL_WATER DESC;

SELECT * FROM us_project.us_household_income_statistics;
SELECT * FROM us_household_income;


#INGRESO PROMEDIO EN LOS ESTADOS
SELECT STATE_NAME, ROUND(AVG(MEAN),0) AVG_SALARY
FROM us_household_income_statistics
GROUP BY State_Name
ORDER BY AVG_SALARY DESC;

#INGRESO PROMEDIO EN LOS ESTADOS Y CITIES PERO LE AGREGAMOS QUE CIUDAD ES LA QUE MEJOR PROMEDIO DE SALARIO TIENE
SELECT * FROM 
	(SELECT STATS.STATE_NAME, 
	INCOM.CITY, 
	ROUND(AVG(MEAN),0) AVG_SALARY,
	ROW_NUMBER () OVER (PARTITION BY STATS.STATE_NAME ORDER BY ROUND(AVG(MEAN),0) DESC) TOP_SALARY
	FROM us_household_income_statistics STATS
	INNER JOIN us_household_income INCOM
	ON STATS.ID = INCOM.ID
	GROUP BY STATS.STATE_NAME, INCOM.CITY) T1
WHERE TOP_SALARY = 1
    ;



#ESTADO CON EL INGRESO PROMEDIO MAS ALTO
SELECT STATS.STATE_NAME,  
	ROUND(AVG(MEAN),0) AVG_SALARY
FROM us_household_income_statistics STATS
INNER JOIN us_household_income INCOM
ON STATS.ID = INCOM.ID
GROUP BY STATS.STATE_NAME
ORDER BY AVG_SALARY DESC
